### ISSUE TITLE
Call did not revert as expected

### ISSUE THREAD

**Issue by Yberjon** [neotheprogramist/era-contracts#43]
#### 📝 Description

I encountered an issue where the function reverts with a message but after adding "vm.expectRevert(msg)" it doesn't revert or reverts with different message.

#### 🔄 Reproduction Steps

Run tests on this branch:
https://github.com/neotheprogramist/era-contracts/tree/test/validator-timelock

To run the tests use "yarn test:foundry --match-contract ValidatorTest --ffi  -vvv". After that uncomment vm.expectReverts and run it again.

#### 🤔 Expected Behavior

After adding vm.expectRevert with a correct message the test should succeed.

#### 😯 Current Behavior

Test fails with and without expectRevert.

#### 🖥️ Environment

Any relevant environment details.

#### 📎 Log Output

![obraz](https://github.com/user-attachments/assets/d4f2581a-2a49-4977-abee-d6a62f8beb4c)

![obraz](https://github.com/user-attachments/assets/da56e54e-ae4f-4e49-94ee-f2b8a1a2e77c)

**Comment by kelemeno** [comment]
Hey, its because you're calling the getMockCommitBatchInfo inside the commitBatchesSharedBridge function, so the expectREvert applies to that and not the commitBatchesSharedBridge function, try this: 

```
    function test_commitWrongBatchNumber() public {
        IExecutor.StoredBatchInfo[] memory storedBatch = getMockStoredBatchInfo(1, 0);

        vm.startBroadcast(chainAdmin);
        validatorTimelock.addValidator(chainId, newValidator);
        vm.stopBroadcast();

        IExecutor.CommitBatchInfo[] memory batch = getMockCommitBatchInfo(1);
        vm.startBroadcast(newValidator);
        vm.expectRevert("DummyExecutor: Invalid last committed batch number");
        validatorTimelock.commitBatchesSharedBridge(chainId, storedBatch[0], batch);
        vm.stopBroadcast();
    }
```

<img width="1231" alt="image" src="https://github.com/user-attachments/assets/d86bdece-8e43-4266-ac94-eec115c74bb6">
